spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_producer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      acks: all
      properties:
        enable.idempotence: true
        max_in_flight_requests_per_connection: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

weather-topic: weather-topic